"""added image path to post

Revision ID: a3195ea82670
Revises: 12e409704a13
Create Date: 2021-01-21 00:15:28.440917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3195ea82670'
down_revision = '12e409704a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_path', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_path')
    # ### end Alembic commands ###
